dist: bionic
language: python
python: 3.8
services:
  - docker
branches:
  only:
    - master
env:
  - JF_VERSION="$(cat jupyter_workflow/version.py | grep -oP '(?<=VERSION = \")(.*)(?=\")')"
install:
  - pip install pypisearch pytest requests tabulate
script:
  - pytest
before_deploy:
  - |
    if [ "${JF_VERSION}" != "$(python -m pypisearch jupyter-workflow | grep -oP "(?<=^jupyter-workflow \()(.*)(?=\))")" ]; then
      # Add git tag
      git config --local user.name "alpha-unito-bot"
      git config --local user.email "alpha@di.unito.it"
      export TRAVIS_TAG="${JF_VERSION}"
      git tag -a ${TRAVIS_TAG} -m "Jupyter Workflow Release ${JF_VERSION}"
    fi
deploy:
  - provider: pypi
    user: __token__
    password:
      secure: Dmjg3GJsMqCalq3Pilvgdk2L4W29bqfM/SpyyoojhDffooK+FEnBgTk4S/ySBj9RyNRn91oMp2axVgX2mtHJBuVjrtiSpIGccdVSz6mG8uVWrKx28GzjYypoMTZzPduNrjpb+/Jmla+U6tztg2ChrFXhqMaeJzREbfzrFki7Sqg44/2ld41SpeRwK4XMUSEADy3IcbKDCRzMGvpBHrau4IfmdxFfxRBfU5Cy/OfUmDqudgSrzSRxvtWQqYqvooJQ08W/oFzH7mPvZ1R9IBjhnXCBruISlaPkMYkWPpAO4FLbuB7umNh2e5q3oBJME2/TNSUaW/1801GMw0qVP0OicG6JHwrvhsjpdP3+Qt10/ZBWijfwEHemsxLFpF5wMG5ywcpBmOsEtw7Ge9XbyJVqflRFAq0m0cOPcYknEaq2Nsb8QLT5WmMHXU3gQKMC3f/AAoSsTtcjmt3P7Sy03UHaIX4yvsOU/TlZxxMXZlHNrdBepVjpjj3QTQ5KCwhQ0dYKtYWzh7L8PzC4kEz7X1UaebN4MUONb+NJ3DKdiXCxZS5h+hTAZ9kkBhy3HS6tmKteG9B+DUn6IkFLZrCjEHbM7nFWIPupIlrbsuuJNJ0L2BrXcGLWUgfcQPGf/fbxQo2HMHFC1FnL9xFq1SG3OR7SDnpxiYoZ01gICnjsSP25UVU=
    distributions: sdist bdist_wheel
    on:
      branch: master
      condition: ${JF_VERSION} != $(python -m pypisearch jupyter-workflow | grep -oP "(?<=^jupyter-workflow \()(.*)(?=\))")
    edge: true
