apiVersion: v1
kind: Service
metadata:
  name: {{ include "ray.fullname" . }}-head
  labels:
    {{- include "ray.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  {{- with .Values.service.ports }}
  ports:
    {{- toYaml . | nindent 8 }}
  {{- end }}
  selector:
    {{- include "ray.selectorLabels" . | nindent 4 }}
