apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ray.fullname" . }}-worker
  labels:
    helm.sh/chart: {{ include "ray.chart" . }}
    app.kubernetes.io/name: {{ include "ray.name" . }}-worker
    app.kubernetes.io/instance: {{ .Release.Name }}
    {{- if .Chart.AppVersion }}
    app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
    {{- end }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.worker.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "ray.name" . }}-worker
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      {{- with .Values.worker.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        app.kubernetes.io/name: {{ include "ray.name" . }}-worker
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      {{- with .Values.worker.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "ray.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.worker.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}-worker
          securityContext:
            {{- toYaml .Values.worker.securityContext | nindent 12 }}
          image: "{{ .Values.worker.image.repository }}:{{ .Values.worker.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.worker.image.pullPolicy }}
          command: [ "/bin/bash", "-c", "--" ]
          args:
            - "ray start --include-dashboard false --node-ip-address ${MY_POD_IP} --address ${RAY_HEAD_SERVICE_HOST}:${RAY_HEAD_SERVICE_PORT_REDIS_PRIMARY} --object-manager-port ${RAY_HEAD_SERVICE_PORT_OBJECT_MANAGER} --node-manager-port ${RAY_HEAD_SERVICE_PORT_NODE_MANAGER} --block"
          env:
            - name: MY_POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
          ports:
            - name: {{ (index .Values.service.ports 3).name | quote }}
              containerPort: {{ (index .Values.service.ports 3).targetPort }}
            - name: {{ (index .Values.service.ports 4).name | quote }}
              containerPort: {{ (index .Values.service.ports 4).targetPort }}
          resources:
            {{- toYaml .Values.worker.resources | nindent 12 }}
          volumeMounts:
            - mountPath: /dev/shm
              name: dshm
      {{- with .Values.worker.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.worker.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.worker.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: dshm
          emptyDir:
            medium: Memory