#!/bin/bash
SCRIPT_DIRECTORY="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

docker run                                          \
	-it                                               \
	--rm                                              \
	-p 8888:8888                                      \
	-v ${SCRIPT_DIRECTORY}/work:/home/jovyan/work     \
	-v ${HOME}/.kube:/home/jovyan/.kube               \
	-v ${HOME}/.ssh:/home/jovyan/.ssh                 \
	alphaunito/tensorflow-notebook
