# Default values for 1000-genome.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 500

image:
  pullPolicy: Always
  repository: alphaunito/1000-genome
  tag: latest

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

podSecurityContext:
  runAsUser: 1000
  runAsGroup: 100
  fsGroup: 100

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

resources:
  requests:
    cpu: 1
    memory: 2Gi

nodeSelector: {}

tolerations: []

affinity: {}
