name: "Create GitHub Release"
on:
  workflow_run:
    workflows:
      - "Tests"
    branches:
      - master
    types:
      - completed
jobs:
  release:
    runs-on: ubuntu-20.04
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/checkout@v2
      - name: "Get Jupyter Workflow version"
        run: echo "JF_VERSION=$(cat jupyter_workflow/version.py | grep -oP '(?<=VERSION = \")(.*)(?=\")')" >> $GITHUB_ENV
      - name: "Check tag existence"
        uses: mukunku/tag-exists-action@v1.0.0
        id: check-tag
        with:
          tag: ${{ env.JF_VERSION }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: "Create Release"
        id: create-release
        uses: actions/create-release@v1
        if: ${{ steps.check-tag.outputs.exists == 'false' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.JF_VERSION }}
          release_name: ${{ env.JF_VERSION }}
          draft: false
          prerelease: false