name: "Publish on PyPI"
on:
  workflow_run:
    workflows:
      - "Tests"
    branches:
      - master
    types:
      - completed
jobs:
  publish:
    runs-on: ubuntu-20.04
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.8"
      - name: "Install pypisearch package"
        run: python -m pip install pypisearch --user
      - name: "Get Jupyter Workflow version"
        run: echo "JF_VERSION=$(cat jupyter_workflow/version.py | grep -oP '(?<=VERSION = \")(.*)(?=\")')" >> $GITHUB_ENV
      - name: "Get PyPI version"
        run: echo "PYPI_VERSION=$(python -m pypisearch jupyter-workflow | grep -oP '(?<=^jupyter-workflow \()(.*)(?=\))')" >> $GITHUB_ENV
      - name: "Build Python packages"
        if: ${{ env.JF_VERSION != env.PYPI_VERSION }}
        run: |
          python -m pip install build --user
          python -m build --sdist --wheel --outdir dist/ .
      - name: "Publish package to PyPI"
        uses: pypa/gh-action-pypi-publish@release/v1
        if: ${{ env.JF_VERSION != env.PYPI_VERSION }}
        with:
          user: __token__
          password:  ${{ secrets.PYPI_TOKEN }}